# Welcome to Lab 1!

Ways to get help:
1. Copy and paste your error messages into google.
2. Use the 'Help' menu above to find the help for the component of jupyter-notebook that you're struggling with.
3. Enter `?command` to get help for a specific `command`. For instance `?np.ndarray.transpose`


## Part 1
We will do some exercises to learn how to use the the numpy and scipy modules included with jupyter. Python itself has only limited functionality for doing numerical calculations, so we will make extensive use of the numpy library (a collection of programs) to do numerical work. In order to load numpy, you will always need to use the 'import' command. For consistency I recommend always importing numpy as np like so:

In [ ]:
import numpy as np

We will very frequently need to work with scalars, vectors, and matrices in order to develop numerical models. Below are examples showing how we can define each.

In [ ]:
a=1.0 # a is a scalar
print("a=",a)
b=np.array([[1., 2., 3., 4., 5.]]) # b is a row vector
print("b=",b)
c=np.array([[1.], [2.], [3.], [4.], [5.]]) # c is a column vector
print("c=",c)

Notice that the way that we entered c above is quite tedious due to the nested square brackets `[]` enclosing each row. Instead of using square brackets, we could instead define c as a row vector and then take its transpose:

In [ ]:
c=np.array([[1., 2., 3., 4., 5.]]).transpose()

In the cell above, we accessed the `transpose()` method of the NumPy array holding our data. NumPy conveniently provides many methods that operate on NumPy arrays. If you want to see a list of all of the available methods, go to Help->NumPy and click on the documentation for `ndarray` OR you can do the following:

In [ ]:
?np.ndarray.*

We can also create matrices and store them using numpy ndarray objects:

In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6], [7,8,9],[10,11,12]])
print(a)

What are the dimensions of the n-dimensional array `a`?

YOUR ANSWER HERE

Frequently, it's convenient to start by creating matrices filled with zeroes. NumPy has a routine to help us accomplish this called `zeroes`:

In [ ]:
zm = np.zeros((8,10))
print("zm=",zm)

In [ ]:
"""We can use the shape method to find the shape of zm."""
print(zm.shape)

In [ ]:
"""Frequently, we will want to loop over the rows in a matrix like zm and modify its contents"""
m, n = zm.shape
for i in range(m):
    zm[i][i] = 1.0 # assign a value of 1.0 to the diagonal entry of each row in zm.
print(zm)

Exercise: write some code to generate the 'Laplacian' operator (a matrix) containing the entries:<br>
`
[[-2  1  0  0  0  0 ... 0  0  0  0] 
 [ 0  1 -2  1  0  0 ... 0  0  0  0]
 [ 0  0  1 -2  1  0 ... 0  0  0  0]
 ...
 [ 0  0  0  0  0  0 ... 0  1 -2  1]
 [ 0  0  0  0  0  0 ... 0  0  1 -2]]`

In [ ]:
def laplacian(n):
    L = np.zeros((n,n)) # create the n-by-n matrix
    # YOUR CODE HERE
    raise NotImplementedError()
    return L

In [ ]:
"""Test for correct output"""
assert( (laplacian(3) == np.array( [[-2.,1.,0.],[1.,-2.,1.],[0.,1.,-2.]])).all() )
assert( (laplacian(4) == np.array( [[-2.,1.,0.,0.],[1.,-2.,1.,0.],[0.,1.,-2.,1.],[0.,0.,1.,-2.]])).all() )
assert( (laplacian(10) == np.array([[-2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.]])).all())